remote_theme: niklasbuschmann/contrast

title: "佶"
title_icon: "/assets/icons/佶.svg"
favicon: "/assets/icons/佶.svg"

show_excerpts: true        # show article excerpts on the home page

plugins:
  - jekyll-remote-theme
